-- AlterEnum
ALTER TYPE "ClaimType" ADD VALUE 'MECHANISM_BIOLOGICAL';
ALTER TYPE "ClaimType" ADD VALUE 'CLINICAL_APPLICATION';
ALTER TYPE "ClaimType" ADD VALUE 'INTERVENTION_PROTOCOL';
ALTER TYPE "ClaimType" ADD VALUE 'INTERVENTION_TECHNOLOGY';
ALTER TYPE "ClaimType" ADD VALUE 'PRODUCT_CLAIM';

-- AlterEnum
ALTER TYPE "ClaimStance" ADD VALUE 'SUGGESTED';
ALTER TYPE "ClaimStance" ADD VALUE 'ANECDOTAL';
